### ISSUE TITLE
Python : RuntimeError: ​[Bitmap] Bitmap::rebuild_struct(): channel count (11)

### ISSUE THREAD

**Issue by boonta** [mitsuba-renderer/mitsuba2#220]
RuntimeError

## Summary
I tried an example rendering script 'render_scene.py' with 'bsdf_spheres' scenes (from resource directory).
It throws a runtime error as follows :

**_File "render_scene.py", line 32, in <module>
    bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.UInt8, srgb_gamma=True).write('output.jpg')
RuntimeError: ​[Bitmap] Bitmap::rebuild_struct(): channel count (11) does not match pixel format (rgb)!_**

## System configuration

Windows 10 / miniconda3 / python3.7 / Mitsuba 2 / packet_rgb 

## Description

Here is the full outputs from running 'python render_scene.py'

(base) D:\mitsuba2\test\bsdf_spheres>python render_scene.py
2020-07-20 15:11:42 INFO  main  [xml.cpp:1182] Loading XML file "test_envmap.xml" ..
2020-07-20 15:11:42 INFO  main  [xml.cpp:1183] Using variant "packet_rgb"
2020-07-20 15:11:42 INFO  main  [xml.cpp:354] "test_envmap.xml": in-memory version upgrade (v2.0.0 -> v2.1.0) ..
2020-07-20 15:11:42 INFO  main  [xml.cpp:639] Loading included XML file "D:\mitsuba2\test\bsdf_spheres\fragments\sphere_grid.xml" ..
2020-07-20 15:11:42 INFO  main  [xml.cpp:354] "D:\mitsuba2\test\bsdf_spheres\fragments\sphere_grid.xml": in-memory version upgrade (v2.0.0 -> v2.1.0) ..
2020-07-20 15:11:42 INFO  main  [PluginManager] Loading plugin "plugins\srgb.dll" ..
2020-07-20 15:11:42 INFO  main  [PluginManager] Loading plugin "plugins\uniform.dll" ..
2020-07-20 15:11:42 INFO  main  [PluginManager] Loading plugin "plugins\envmap.dll" ..
2020-07-20 15:11:42 INFO  tbb01 [PluginManager] Loading plugin "plugins\diffuse.dll" ..
2020-07-20 15:11:42 INFO  tbb00 [PluginManager] Loading plugin "plugins\roughdielectric.dll" ..
2020-07-20 15:11:42 INFO  tbb03 [PluginManager] Loading plugin "plugins\box.dll" ..
2020-07-20 15:11:42 INFO  tbb03 [PluginManager] Loading plugin "plugins\hdrfilm.dll" ..
2020-07-20 15:11:42 INFO  tbb02 [PluginManager] Loading plugin "plugins\path.dll" ..
2020-07-20 15:11:42 INFO  tbb05 [PluginManager] Loading plugin "plugins\bitmap.dll" ..
2020-07-20 15:11:42 INFO  tbb06 [PluginManager] Loading plugin "plugins\plastic.dll" ..
2020-07-20 15:11:42 INFO  tbb01 [PluginManager] Loading plugin "plugins\obj.dll" ..
2020-07-20 15:11:42 INFO  tbb04 [PluginManager] Loading plugin "plugins\dielectric.dll" ..
2020-07-20 15:11:42 INFO  tbb03 [PluginManager] Loading plugin "plugins\independent.dll" ..
2020-07-20 15:11:42 INFO  tbb02 [PluginManager] Loading plugin "plugins\moment.dll" ..
2020-07-20 15:11:42 INFO  main  [PluginManager] Loading plugin "plugins\conductor.dll" ..
2020-07-20 15:11:42 INFO  tbb03 [PluginManager] Loading plugin "plugins\perspective.dll" ..
2020-07-20 15:11:42 INFO  tbb02 [PluginManager] Loading plugin "plugins\twosided.dll" ..
2020-07-20 15:11:42 INFO  tbb03 [PluginManager] Loading plugin "plugins\roughplastic.dll" ..
2020-07-20 15:11:42 INFO  tbb01 [PluginManager] Loading plugin "plugins\mask.dll" ..
2020-07-20 15:11:42 INFO  tbb01 [PluginManager] Loading plugin "plugins\roughconductor.dll" ..
2020-07-20 15:11:43 INFO  main  [ShapeKDTree] Building a SAH kd-tree (325124 primitives) ..
2020-07-20 15:11:44 INFO  main  [ShapeKDTree] Finished. (27 MiB of storage, took 1.9s)
2020-07-20 15:11:44 INFO  main  [SamplingIntegrator] Starting render job (48x48, 128 samples, 8 threads)
Rendering [=====================================================================================] (182ms, ETA: 0ms)     
2020-07-20 15:11:45 INFO  main  [SamplingIntegrator] Rendering finished. (took 183ms)
2020-07-20 15:11:45 INFO  main  [HDRFilm] ?  Developing "output.exr" ..
Traceback (most recent call last):
  File "render_scene.py", line 32, in <module>
    bmp.convert(Bitmap.PixelFormat.RGB, Struct.Type.UInt8, srgb_gamma=True).write('output.jpg')
RuntimeError: ​[Bitmap] Bitmap::rebuild_struct(): channel count (11) does not match pixel format (rgb)!

-----------------------------------------------
It generates an exr output file but it seems the channel count is 11 (which I do not think it is correct.).
Moreover, when I open the EXR output file, the background shows nothing (checker board in the background).

![ฟฟฟฟ](https://user-images.githubusercontent.com/2579302/87915488-741d2f00-ca9c-11ea-85f7-c07986db748d.jpg)

**Comment by ankus-wu** [comment]
When I am running direct_integrator.py, I get the similar error:
`RuntimeError: ​[Bitmap] Bitmap::rebuild_struct(): channel count (6) does not match pixel format (rgb)!`
I find the channel of bitmap is 6, which is expected to 3.
I don't know why is it.

**Comment by ankus-wu** [comment]
When I return an empty list from aov_names, the Bitmap is XYZAW structure.

**Comment by Speierers** [comment]
How do you get the `Bitmap` object? Could it be that you set the `raw` argument to `True`? In which case it should return an `XYZAW` Bitmap.

**Comment by ankus-wu** [comment]
> How do you get the `Bitmap` object? Could it be that you set the `raw` argument to `True`? In which case it should return an `XYZAW` Bitmap.

Yes, I set the `raw` argument to `True` by default. The question is that an `XYZAW` Bitmap is desired, but when I return a non-empty list from `aov_names` function, the Bitmap has six channels.

**Comment by Speierers** [comment]
Right, then you need to `split()`. Also I think it might be that this method discards doesn't set the proper pixel format, which you can force as follow:
```
b_raw = film.bitmap(raw=True)
b_first = Bitmap(np.array(b_raw.split()[0][1], copy=False), Bitmap.PixelFormat.XYZAW)
b = b_first.convert(Bitmap.PixelFormat.RGBA, Struct.Type.Float32, srgb_gamma=True)
```

This will be fixed in the upcoming release of the framework :)
