### ISSUE TITLE
[❔ other question] Custom higher dimensional variant

### ISSUE THREAD

**Issue by LeonardEyer** [mitsuba-renderer/mitsuba2#327]
## Summary

I am having trouble compiling a custom variant using a Spectrum with 8 entries instead of 4. Is this expected?

## System configuration

- Desired variant:
```
"scalar_spectral8": {
        "float": "float",
        "spectrum": "Spectrum<Float, 8>"
    },
```

## Description
Maybe I am missing something but I feel like this should be possible. I would like to add custom plugins that use this kind of spectrum.

**Comment by Speierers** [comment]
Hi @LeonardEyer ,

What's the problem when compiling this variant? Could you share the compiler/runtine error logs here please.

Along with you system specs, that would be great.

**Comment by LeonardEyer** [comment]
Sure! The variant actually compiles but I am not able to use set_variant when using the python bindings. 

```
>>> mitsuba.set_variant("packet_spectral8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leonardeyer/codetemp/mitsuba2/cmake-build-debug/dist/python/mitsuba/__init__.py", line 162, in set_variant
    _import('mitsuba.core_' + value + '_ext')),
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1108, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: pybind11_type_alias(): source type not found!

```
- Platform: MacOS 10.14.6
- Compiler: Clang11
- Python version: 3.9
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `scalar_spectral8`

I also tried compiling a spectral5 variant which resulted in the following error.

```
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_masked.h:28:85: error: use of overloaded operator '=' is ambiguous (with operand types 'enoki::Array<float, 5>' and 'const mitsuba::Spectrum<float, 5>')
    template <typename T2> ENOKI_INLINE void operator =(const T2 &value) { if (m) d = value; }
                                                                                  ~ ^ ~~~~~
/Users/leonardeyer/codetemp/mitsuba2/src/integrators/volpathmis.cpp:456:45: note: in instantiation of function template specialization 'enoki::detail::MaskedValue<enoki::Array<float, 5> >::operator=<mitsuba::Spectrum<float, 5> >' requested here
                masked(p_over_f[i], active) = select(enoki::isfinite(ratio), ratio, 0.f);
                                            ^
/Users/leonardeyer/codetemp/mitsuba2/src/integrators/volpathmis.cpp:176:21: note: in instantiation of member function 'mitsuba::VolpathMisIntegratorImpl<float, mitsuba::Spectrum<float, 5>, true>::update_weights' requested here
                    update_weights(p_over_f, free_flight_pdf, tr, channel, is_spectral);
                    ^
/Users/leonardeyer/codetemp/mitsuba2/src/integrators/volpathmis.cpp:72:5: note: in instantiation of member function 'mitsuba::VolpathMisIntegratorImpl<float, mitsuba::Spectrum<float, 5>, true>::sample' requested here
    VolpathMisIntegratorImpl(const Properties &props) : Base(props) {}
    ^
/Users/leonardeyer/codetemp/mitsuba2/src/integrators/volpathmis.cpp:48:37: note: in instantiation of member function 'mitsuba::VolpathMisIntegratorImpl<float, mitsuba::Spectrum<float, 5>, true>::VolpathMisIntegratorImpl' requested here
            result = (Object *) new Impl<true>(m_props);
                                    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_recursive.h:30:5: note: candidate function
    ENOKI_ARRAY_IMPORT_BASIC(Base, StaticArrayImpl)
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:129:5: note: expanded from macro 'ENOKI_ARRAY_IMPORT_BASIC'
    ENOKI_ARRAY_DEFAULTS(Array)                                                \
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:125:12: note: expanded from macro 'ENOKI_ARRAY_DEFAULTS'
    Array &operator=(Array &&) = default;
           ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array.h:83:5: note: candidate function
    ENOKI_ARRAY_IMPORT(Base, Array)
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:138:5: note: expanded from macro 'ENOKI_ARRAY_IMPORT'
    ENOKI_ARRAY_IMPORT_BASIC(Base, Array)                                      \
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:129:5: note: expanded from macro 'ENOKI_ARRAY_IMPORT_BASIC'
    ENOKI_ARRAY_DEFAULTS(Array)                                                \
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:125:12: note: expanded from macro 'ENOKI_ARRAY_DEFAULTS'
    Array &operator=(Array &&) = default;
           ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_recursive.h:30:5: note: candidate function
    ENOKI_ARRAY_IMPORT_BASIC(Base, StaticArrayImpl)
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:129:5: note: expanded from macro 'ENOKI_ARRAY_IMPORT_BASIC'
    ENOKI_ARRAY_DEFAULTS(Array)                                                \
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:124:12: note: expanded from macro 'ENOKI_ARRAY_DEFAULTS'
    Array &operator=(const Array &) = default;                                 \
           ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array.h:83:5: note: candidate function
    ENOKI_ARRAY_IMPORT(Base, Array)
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:138:5: note: expanded from macro 'ENOKI_ARRAY_IMPORT'
    ENOKI_ARRAY_IMPORT_BASIC(Base, Array)                                      \
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:129:5: note: expanded from macro 'ENOKI_ARRAY_IMPORT_BASIC'
    ENOKI_ARRAY_DEFAULTS(Array)                                                \
    ^
/Users/leonardeyer/codetemp/mitsuba2/ext/enoki/include/enoki/array_generic.h:124:12: note: expanded from macro 'ENOKI_ARRAY_DEFAULTS'
    Array &operator=(const Array &) = default;                                 \
           ^
1 error generated.
make[2]: *** [src/integrators/CMakeFiles/volpathmis-obj.dir/volpathmis.cpp.o] Error 1
make[1]: *** [src/integrators/CMakeFiles/volpathmis-obj.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Built target tent-obj
[ 35%] Built target lanczos-obj
make: *** [all] Error 2
```

**Comment by Speierers** [comment]
When trying to set this variant in Python, it complains that the `Spectrum` type doesn't have proper bindings. This is mostly likely coming from the following lines in `main_v.cpp`:
```
if constexpr (is_spectral_v<UnpolarizedSpectrum>)
        pybind11_type_alias<Array<Float, UnpolarizedSpectrum::Size>,
                            UnpolarizedSpectrum>();
```

This is something that we could fix in the upcoming refactored version of Mitsuba. In the meantime, I would recommend that you comment out those two lines if you don't need the `Spectrum` type in python directly. Otherwise you will need to add those bindings to enoki itself. For this you could try to copy the `enoki/src/python/scalar_4d.cpp` and change `4->8` although I do not guarantee that this will compile.

Regarding the compilation errors with `Spectrum5`, this will involve some deeper changes to enoki, which won't happen as we are now focussing on the upcoming refactored version of it.

**Comment by LeonardEyer** [comment]
I tried uncommenting the lines but this results in the following error:
```
ImportError: AttributeError: UnpolarizedSpectrum
```

The approach to add the bindings to enoki worked like a charm though. Thanks for the quick and effective help!

**Comment by arpit15** [comment]
@LeonardEyer Do you have the implementation of your updated bindings for `spectral8` ?  I tried to add to add similar bindings for `spectral23`. However, I get a lot of compilation errors. Could you kindly share your updated bindings?
