### ISSUE TITLE
How to use it within python after compilation

### ISSUE THREAD

**Issue by nik85** [mitsuba-renderer/mitsuba2#37]
Dear developers,

compilation was done without any error. Still, I am not able to correctly import mitsuba as module in python. After compilation of the repository, I copied the mitsuba and enoki folder from the dist folder to the site-packages of the python environment.

However the import fails with the following error:

```
C:\Users\nik\AppData\Local\Programs\Python\Python38\python.exe C:/Users/nik/PycharmProjects/diff_render/tutorial.py
Traceback (most recent call last):
  File "C:\Users\nik\AppData\Local\Programs\Python\Python38\lib\site-packages\mitsuba\__init__.py", line 12, in <module>
    _import('mitsuba.core_ext')
  File "C:\Users\nik\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing core_ext: Das angegebene Modul wurde nicht gefunden.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/nik/PycharmProjects/diff_render/tutorial.py", line 1, in <module>
    import mitsuba
  File "C:\Users\nik\AppData\Local\Programs\Python\Python38\lib\site-packages\mitsuba\__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported.
```

As a sidenote - tutorial.py contains the following
```
import mitsuba
mitsuba.set_variant('gpu_autodiff_rgb')
```
Do you have any suggestion how to fix this behavior? 

However if I use mitsuba2/dist as project root that includes enoki and mitsuba i am able to import mitsuba. While still a similar error occurs but at least the mitsuba.core_ext could be imported.

```
Traceback (most recent call last):
  File "C:\Users\nik\PycharmProjects\mitsuba2\dist\python\mitsuba\__init__.py", line 13, in <module>
    _import('mitsuba.render_ext')
  File "C:\Users\nik\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/nik/PycharmProjects/mitsuba2/dist/tut.py", line 1, in <module>
    import mitsuba
  File "C:\Users\nik\PycharmProjects\mitsuba2\dist\python\mitsuba\__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. 
```

So if I change mitsuba init.py to:
```
if sys.version_info < (3, 6):
    raise ImportError("Mitsuba requires Python 3.6 or greater.")

try:
    _import('mitsuba.core_ext')
    # _import('mitsuba.render_ext')
    _tls = threading.local()
``` 

I can at least import mitsuba without errors. However I do not understand why the other import fails.

**Comment by nik85** [comment]
Ok seemed to be my own fault. Since it was not possible to import render_ext, somebody with more experience might have noticed that there might be an issue with the gpu libraries while compiling.

However, cmake did not abort with an error message and compiled smoothly.
It was not enough to only add cmake .. -DMTS_OPTIX_PATH="" to the cmake command, but also necessarry to set the path variable to "C:\ProgramData\NVIDIA Corporation\OptiX SDK 6.5.0\bin64".

It became obvious when running mitsuba.exe from cmd occurred with the error that optix.6.5.0.dll was not found/installed. 

Since i never tried to run it, it only gave me this strange import error within python.

**Comment by Speierers** [comment]
Thanks @nik85 for your feedbacks!

We strongly recommand to use the `setpath.sh` script to add the compiled Mitsuba module to your Python path instead of manually copying those in your site-package folder.

```bash
# After building (on Linux)
source setpath.sh
```

Regarding the missing CMake error message when `Optix/bin` is missing from the path, I will add a line in the doc.

**Comment by atuyoti** [comment]
Dear @Speierers 
I have the same problem.
I tried to add cmake .. -DMTS_OPTIX_PATH="C:\ProgramData\NVIDIA Corporation\Optix SDK 6.5.0" to the cmake command, and to set the path variable to "C:\ProgramData\NVIDIA Corporation\OptiX SDK 6.5.0\bin64".

Error message is shown below.

`(base)  @C:\Users\AOTO_FAB\Desktop\Atuyoti\mitsuba2>setpath.bat
(base) C:\Users\AOTO_FAB\Desktop\Atuyoti\mitsuba2>cd C:\Users\AOTO_FAB\Desktop\Atuyoti\mitsuba2\docs\examples\01_render_scene
(base) C:\Users\AOTO_FAB\Desktop\Atuyoti\mitsuba2\docs\examples\01_render_scene>python render_scene.py
Traceback (most recent call last):
  File "C:\Users\AOTO_FAB\Desktop\Atuyoti\mitsuba2\build\dist\python\mitsuba\__init__.py", line 12, in <module>
    _import('mitsuba.core_ext')
  File "C:\Users\AOTO_FAB\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mitsuba.core_ext'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "render_scene.py", line 3, in <module>
    import mitsuba
  File "C:\Users\AOTO_FAB\Desktop\Atuyoti\mitsuba2\build\dist\python\mitsuba\__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (C:\Users\AOTO_FAB\anaconda3\python.exe) that is different from the one for which the native module was compiled (C:\Users\AOTO_FAB\AppData\Local\Programs\Python\Python38\python.exe).`


**System configuration**
windows10
Optix SDK 6.5.0
cmake 3.16.8
python 3.7.6

**Comment by nik85** [comment]
To me it seems that you have a different error. It states that you were compiling against Python3.8 in the last line.
However you mentioned python 3.7.6 in your system configuration. I had a similar error when I was using miniconda. 
The problem is, that there seems to be a fallback or lookup on the "default" python version when using cmake, which seems to be the anaconda 3.8 one in your case. This is path is by default set in your path environment, thats why it was used for compilation. Just add your python3.7.6. folder to path and either remove the anaconda base directory. At least temporarily.

**Comment by atuyoti** [comment]
@nik85 
Thanks for your advice.
It worked!!
