### ISSUE TITLE
RuntimeError: ​[distr_1d.h:84] DiscreteDistribution: no probability mass found!

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2#512]
- [🐛 bug report]

## Summary

what an error this is?

```
Traceback (most recent call last):
  File "invert_heightfield.py", line 165, in <module>
    pre_render_callback=apply_displacement)
  File "/home/zhuxiangyang/mitsuba2/build/dist/python/mitsuba/python/autodiff.py", line 190, in render
    pre_render_callback()
  File "invert_heightfield.py", line 136, in apply_displacement
    params.update()
  File "/home/zhuxiangyang/mitsuba2/build/dist/python/mitsuba/python/util.py", line 120, in update
    node.parameters_changed(keys)
RuntimeError: ​[distr_1d.h:84] DiscreteDistribution: no probability mass found!
Segmentation fault (core dumped)
```

## System configuration

- Platform: Ubantu 18.04
- Compiler: cuda 11.0
- Python version: 3.8
- Mitsuba 2 version: 2.2.1
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`
    * `packet_spectral`
    * `gpu_autodiff_spectral`
    * `gpu_autodiff_rgb`
    * `gpu_autodiff_mono`
- Hardware: RTX 3090

**Comment by merlinND** [comment]
Hello @HsiangYangChu,

Please check out the code that led to this exception:

https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/include/mitsuba/core/distr_1d.h#L67-L84

Based on that you should be able to figure out what happen in the script, that then caused this issue to occur.

Feel free to reopen if you believe there's a Mitsuba 2 bug causing this problem.

**Comment by HsiangYangChu** [comment]
> Hello @HsiangYangChu,
> 
> Please check out the code that led to this exception:
> 
> https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/include/mitsuba/core/distr_1d.h#L67-L84
> 
> Based on that you should be able to figure out what happen in the script, that then caused this issue to occur.
> 
> Feel free to reopen if you believe there's a Mitsuba 2 bug causing this problem.

I wonder if other people have experienced similar situations? Actually, the code is one of the recommended codes in docs:
```
import os
import time
import enoki as ek

import mitsuba
mitsuba.set_variant('gpu_autodiff_rgb')

from mitsuba.core import Thread, xml, UInt32, Float, Vector2f, Vector3f, Transform4f, ScalarTransform4f
from mitsuba.render import SurfaceInteraction3f
from mitsuba.python.util import traverse
from mitsuba.python.autodiff import render, write_bitmap, Adam

# Convert flat array into a vector of arrays (will be included in next enoki release)
def ravel(buf, dim = 3):
    idx = dim * UInt32.arange(ek.slices(buf) // dim)
    if dim == 2:
        return Vector2f(ek.gather(buf, idx), ek.gather(buf, idx + 1))
    elif dim == 3:
        return Vector3f(ek.gather(buf, idx), ek.gather(buf, idx + 1), ek.gather(buf, idx + 2))

# Return contiguous flattened array (will be included in next enoki release)
def unravel(source, target, dim = 3):
    idx = UInt32.arange(ek.slices(source))
    for i in range(dim):
        ek.scatter(target, source[i], dim * idx + i)

# Prepare output folder
output_path = "output/invert_heightfield/"
if not os.path.isdir(output_path):
    os.makedirs(output_path)


def make_scene(integrator, spp):
    return xml.load_string("""
        <?xml version="1.0"?>
        <scene version="2.0.0">
            {integrator}
            <emitter type="envmap" id="my_envmap">
                <string name="filename" value="./bunny/museum.exr"/>
            </emitter>
            <sensor type="perspective">
                <string name="fov_axis" value="smaller"/>
                <float name="near_clip" value="0.1"/>
                <float name="far_clip" value="2800"/>
                <float name="focus_distance" value="1000"/>
                <transform name="to_world">
                    <lookat origin="0, 0, 9" target="0, 0, 0" up="0, 1, 0"/>
                </transform>
                <float name="fov" value="15"/>
                <sampler type="independent">
                    <integer name="sample_count" value="{spp}"/>
                </sampler>
                <film type="hdrfilm">
                    <integer name="width" value="256"/>
                    <integer name="height" value="256"/>
                    <rfilter type="box" >
                        <float name="radius" value="0.5"/>
                    </rfilter>
                </film>
            </sensor>

            <shape type="obj" id="smooth_area_light_shape">
                <transform name="to_world">
                    <rotate x="1" angle="180"/>
                    <translate x="10.0" y="0.0" z="15.0"/>
                </transform>
                <string name="filename" value="data/meshes/xy_plane.obj"/>
                <emitter type="area">
                    <spectrum name="radiance" value="1"/>
                </emitter>
            </shape>

            <shape type="obj" id="object">
                <string name="filename" value="data/meshes/smooth_empty_cube.obj"/>
                <bsdf type="diffuse" id="objectmat">
                </bsdf>
                <transform name="to_world">
                    <translate z="0.0"/>
                </transform>    
            </shape>

            <shape type="obj" id="planemesh">
                <string name="filename" value="data/meshes/xy_plane.obj"/>
                
                <bsdf type="diffuse" id="planemat">
                </bsdf>
                
                <transform name="to_world">
                    <translate z="-1"/>
                    <scale value="2.0"/>
                </transform>    
            </shape>
        </scene>
    """.format(integrator=integrator, spp=spp))

# Define integrators for this test

path_str =  """<integrator type="path">
                   <integer name="max_depth" value="2"/>
               </integrator>"""

path_reparam_str =  """<integrator type="pathreparam">
                           <integer name="max_depth" value="3"/>
                       </integrator>"""
                
# scene_folder = './bunny/'
# Thread.thread().file_resolver().append(scene_folder)
# scene = xml.load_file(scene_folder + 'bunny.xml')
scene = make_scene(path_reparam_str, 32)

params = traverse(scene)
positions_buf = params['object.vertex_positions_buf']
positions_initial = ravel(positions_buf)
# print('positions_initial:')
# print(positions_initial)
normals_initial = ravel(params['object.vertex_normals_buf'])
vertex_count = ek.slices(positions_initial)

# Create a texture with the reference displacement map
disp_tex = xml.load_dict({
    "type" : "bitmap",
    "filename" : "mitsuba_coin.jpg",
    "to_uv" : ScalarTransform4f.scale([1, -1, 1]) # texture is upside-down
}).expand()[0]

# Create a fake surface interaction with an entry per vertex on the mesh
mesh_si = SurfaceInteraction3f.zero(vertex_count)
mesh_si.uv = ravel(params['object.vertex_texcoords_buf'], dim=2)
# print(mesh_si)

# Evaluate the displacement map for the entire mesh
disp_tex_data_ref = disp_tex.eval_1(mesh_si)

# Apply displacement to mesh vertex positions and update scene (e.g. OptiX BVH)
def apply_displacement(amplitude = 0.05):
    new_positions = disp_tex.eval_1(mesh_si) * normals_initial * amplitude + positions_initial
    unravel(new_positions, params['object.vertex_positions_buf'])
    params.set_dirty('object.vertex_positions_buf')
    params.update()

# Apply displacement before generating reference image
apply_displacement()

# Render a reference image (no derivatives used yet)
image_ref = render(scene, spp=32)
crop_size = scene.sensors()[0].film().crop_size()
write_bitmap(output_path + 'out_1000.png', image_ref, crop_size)
print("Write " + output_path + "out_1000.png")

# Reset texture data to a constant
disp_tex_params = traverse(disp_tex)
print(disp_tex_params)
disp_tex_params.keep(['data'])
disp_tex_params['data'] = ek.full(Float, 0.25, len(disp_tex_params['data']))
disp_tex_params.update()

# Construct an Adam optimizer that will adjust the texture parameters
opt = Adam(disp_tex_params, lr=0.002)

time_a = time.time()

iterations = 1000
for it in range(iterations):
    # Perform a differentiable rendering of the scene
    image = render(scene,
                   optimizer=opt,
                   spp=4,
                   unbiased=True,
                   pre_render_callback=apply_displacement)

    write_bitmap(output_path + 'out_%03i.png' % it, image, crop_size)

    # Objective: MSE between 'image' and 'image_ref'
    ob_val = ek.hsum(ek.sqr(image - image_ref)) / len(image)

    # Back-propagate errors to input parameters
    ek.backward(ob_val)

    # Optimizer: take a gradient step -> update displacement map
    opt.step()

    # Compare iterate against ground-truth value
    err_ref = ek.hsum(ek.sqr(disp_tex_data_ref - disp_tex.eval_1(mesh_si)))
    print('Iteration %03i: error=%g' % (it, err_ref[0]), end='\r')

time_b = time.time()

print()
print('%f ms per iteration' % (((time_b - time_a) * 1000) / iterations))
```

**Comment by leroyvn** [comment]
Hi @HsiangYangChu, last time I saw this, it was a locale issue (strings containing floating point numbers are parsed according to the current locale while the rest of the code basically assumes `en_US`). Maybe this is what you're experiencing?
