### ISSUE TITLE
python module import failed

### ISSUE THREAD

**Issue by jakoaltrd** [mitsuba-renderer/mitsuba2#602]
when I import python module
_import enoki as ek
import mitsuba
mitsuba.set_variant('gpu_autodiff_rgb')
from mitsuba.core import Thread
from mitsuba.core.xml import load_file
from mitsuba.python.util import traverse
Thread.thread().file_resolver().append('cbox')
scene = load_file('cbox/cbox.xml')
params = traverse(scene)
print(params)_
it always shows
_Traceback (most recent call last):
  File "D:\mitsuba2\mitsuba2\diff.py", line 1, in <module>
    import enoki as ek
ModuleNotFoundError: No module named 'enoki'_

**Comment by jakoaltrd** [comment]
I run setpath.bat, there is no response, the environment is not set, then I set the variants manually, it still shows couldn't load the mitsuba module, I think I didn't set the environment correctly.
PYTHONPATH=D:\mitsuba2\mitsuba2\build\dist\python
path= D:\mitsuba2\mitsuba2\build\dist\python + D:\mitsuba2\mitsuba2\build\dist;

**Comment by Speierers** [comment]
Could you maybe try this from a Conda terminal?

**Comment by jakoaltrd** [comment]
> Could you maybe try this from a Conda terminal?

 I tried with miniconda , it shows:
(base) PS C:\Users\sunsh> D:\mitsuba2\mitsuba2\docs\examples\10_inverse_rendering\invert_bunny.py
(base) PS C:\Users\sunsh> python
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mitsuba
Traceback (most recent call last):
  File "D:\mitsuba2\mitsuba2\build\dist\python\mitsuba\__init__.py", line 12, in <module>
    _import('mitsuba.core_ext')
  File "C:\tools\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mitsuba.core_ext'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\mitsuba2\mitsuba2\build\dist\python\mitsuba\__init__.py", line 33, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (C:\tools\miniconda3\python.exe) that is different from the one for which the native module was compiled (C:\Users\sunsh\AppData\Local\Programs\Python\Python38\python.exe).

**Comment by merlinND** [comment]
Hi @jakoaltrd,

As the error message indicates, you have to build Mitsuba with the same Python version that you're going to use later. It looks like you have 3 different Python installations:

- C:\Users\sunsh\AppData\Local\Programs\Python\Python38\python.exe
- C:\tools\miniconda3\python.exe
- /usr/bin/python3.8 (maybe this one is WSL?)

If you delete your `build` folder and run the CMake configuration step from the Conda terminal (or alternatively, setting the path to Python in the CMake GUI), you should be able to both compile and run with Conda's Python.

**Comment by jakoaltrd** [comment]
> thanks , it is solved after recompile the source, but another issues occurs,

Traceback (most recent call last):
  File "D:\mitsuba2\mitsuba2\docs\examples\10_inverse_rendering\invert_cbox.py", line 59, in <module>
    err_ref = ek.hsum(ek.sqr(param_ref - params['green.reflectance.values']))
RuntimeError: cuda_trace_append(): arithmetic involving arrays of incompatible size (76 and 3). The instruction was "sub.rn.ftz.$t1 $r1, $r2, $r3".

> Hi @jakoaltrd,
> 
> As the error message indicates, you have to build Mitsuba with the same Python version that you're going to use later. It looks like you have 3 different Python installations:
> 
> * C:\Users\sunsh\AppData\Local\Programs\Python\Python38\python.exe
> * C:\tools\miniconda3\python.exe
> * /usr/bin/python3.8 (maybe this one is WSL?)
> 
> If you delete your `build` folder and run the CMake configuration step from the Conda terminal (or alternatively, setting the path to Python in the CMake GUI), you should be able to both compile and run with Conda's Python.

**Comment by jakoaltrd** [comment]
change the variant from gpu_autodiff_spectral to apu_autodiff_rgb addressed the issue, why spectral is not working?

**Comment by njroussel** [comment]
Hi @jakoaltrd !

The spectral variant does work. The error you were seeing was raised because the example `invert_cbox.py` was written in a manner which can only handle RGB. [On line 35](https://github.com/mitsuba-renderer/mitsuba2/blob/master/docs/examples/10_inverse_rendering/invert_cbox.py#L35), the reflectance that we are optimizing is set to an RGB value (3 components). However, the reference reflectance which is saved on [line 26](https://github.com/mitsuba-renderer/mitsuba2/blob/master/docs/examples/10_inverse_rendering/invert_cbox.py#L35) is dependent on the variant - in your case it is a spectral value (76 components). The error is raised when computing the error, where we need to compare both reflectance which have different sizes when using a spectral variant.

**Comment by jakoaltrd** [comment]
thanks, it helps me a lot

**Comment by Speierers** [comment]
@jakoaltrd this is really well explained in the [documentation](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/variants.html#part-2-color-representation) if you are interested.

Glad we could help you with this issue.
